apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: businessdataservice
  labels:
    app: businessdataservice
    version: latest
  namespace: dtag-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: businessdataservice
      version: latest
  template:
    metadata:
      name: businessdataservice
      labels:
        app: businessdataservice
        version: latest
    spec:
      containers:
      - name: businessdataservice
        image: 10.0.5.16:5000/bm/businessdataservice:latest
        args: ["--spring.profiles.active=onap"]
        imagePullPolicy: Always
      imagePullSecrets:
      - name: onap
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
        ports:
        - containerPort: 10001
