apiVersion: v1
kind: Service
metadata:
  name: businessdataservice-svc
  namespace: dtag-dev
  labels:
    app: businessdataservice
    version: latest
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 19001
    nodePort: 32001
    targetPort: 10001
    protocol: TCP
  selector:
    app: businessdataservice
    version: latest
